FROM ubuntu:18.04

MAINTAINER nz "z"

RUN apt-get update && apt-get install python3 -y && apt-get install python3-pip -y &&\
    apt-get install curl -y

COPY ./requirements.txt /requirements.txt

WORKDIR /

RUN pip3 install -r requirements.txt

COPY . /



ENTRYPOINT [ "python3"]

CMD ["app/app.py"]